---

- name: restart nessusagent
  service:
    name: nessusagent
    state: restarted
  become: yes
  when:
  - ansible_os_family is defined
  - ansible_os_family == "RedHat"

- name: start Tenable Nessus Agent
  win_service:
    name: Tenable Nessus Agent
    state: started
  when: ansible_connection == "winrm"

- name: restart Tenable Nessus Agent
  win_service:
    name: Tenable Nessus Agent
    state: restarted
  when: ansible_connection == "winrm"
